# -*- coding: utf-8 -*-
"""cv_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJ0vAwCtncqG1GEMyMpejTpcx6wu_ndQ
"""

import cv2
import matplotlib.pyplot as plt

image_path = '/content/dahlia-1508785047.jpg.avif'
image = cv2.imread(image_path)

# rgb image show

if image is None:
  print("error no image")
else:
  image_rgb = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
  plt.figure(figsize=(8,6))
  plt.axis('off')
  plt.title("flower", fontsize=20,color='pink',pad=15)
  plt.imshow(image_rgb)
  plt.show()

#gray image

image = cv2.imread(image_path)

gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
plt.figure(figsize=(6,6))
plt.axis('off')
plt.title("flower", fontsize=20,color='pink',pad=15)
plt.imshow(gray_image,cmap='gray')
plt.show()

#resize image

image = cv2.imread(image_path)
image_rgb= cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

scale_fact = 0.3
resized_image = cv2.resize(image_rgb,None , fx=scale_fact ,fy=scale_fact)

new_height,new_width = resized_image.shape[:2]
ori_height,ori_width = image_rgb.shape[:2]

print(f"original res = {ori_width}x{ori_height}")
print(f"new res= {new_width}x{new_height}")



plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title(
        "Original ",
        fontsize=16,
        color="darkblue"
    )

    # Blurred ROI
plt.subplot(1, 2, 2)
plt.imshow(resized_image)
plt.title(
"reszed",
           fontsize=16,
        color="darkred"
    )

plt.show()

#blur

image = cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

blur_image = cv2.GaussianBlur(image_rgb , (41,31), 0)

plt.imshow(blur_image)
plt.title("blur image", color='blue', fontsize=10)
plt.show()

#croppimg

image=cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

height,width = image_rgb.shape[:2]

mid_x = width // 2

cropped_img_left = image_rgb[:,:mid_x]
cropped_img_right = image_rgb[:,mid_x:]

plt.subplot(1,3,1)
plt.imshow(cropped_img_right)
plt.title("croopped right")

plt.subplot(1,3,2)
plt.imshow(cropped_img_left)
plt.title("left crop")

plt.subplot(1,3,3)
plt.imshow(image_rgb)
plt.title("original")


plt.show()

#text on img

image=cv2.imread(image_path)

image_rgb=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

text = "FLOWERRR"
font=cv2.FONT_HERSHEY_SIMPLEX

cv2.putText(image_rgb, text,(110,110),font,5,(255,60,100),2)

plt.imshow(image_rgb)
plt.show()

# analyse image using pandas
import pandas as pd
from IPython.display import display

image = cv2.imread(image_path)

flat_img = image.reshape(-1,3)
img_df = pd.DataFrame(flat_img, columns=['B','G','R'])

print('basic staticts')
display(img_df.describe())

# image thresholdin

image = cv2.imread(image_path)

gray_img = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)

ret, thres_img = cv2.threshold(gray_img , 100,200, cv2.THRESH_BINARY)

plt.imshow(thres_img , cmap='gray')
plt.show()

# rotation


image=cv2.imread(image_path)

image_rgb=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

height,width = image_rgb.shape[:2]

center = (width/2 , height/2)
rot_matrix = cv2.getRotationMatrix2D(center , 160,1)
rot_img = cv2.warpAffine(image_rgb , rot_matrix,(width,height))

plt.imshow(rot_img)
plt.show()

# blendin

image_path2 = '/content/gettyimages-2165950545-69600af8c9b0d.jpg.avif'

image1 = cv2.imread(image_path)
image2 = cv2.imread(image_path2)

image1_rgb=cv2.cvtColor(image1,cv2.COLOR_BGR2RGB)
image2_rgb=cv2.cvtColor(image2,cv2.COLOR_BGR2RGB)




target_height, target_width = image2_rgb.shape[:2]
image1_resized = cv2.resize(image1_rgb , (target_width,target_height))

blend_img = cv2.add(image1_resized , image2_rgb)

plt.imshow(blend_img)
plt.show()

image = cv2.imread(image_path , cv2.IMREAD_GRAYSCALE)

eq_img = cv2.equalizeHist(image)

plt.imshow(eq_img, cmap='gray')
plt.show()

# affine , linear , roation

image = cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

height,width = image_rgb.shape[:2]
center = (width//2 , height//2)
angle = 45
scale = 1

matrix = cv2.getRotationMatrix2D(center,angle,scale)

rotated = cv2.warpAffine(image_rgb , matrix , (width,height))

plt.subplot(1,2,1)
plt.imshow(image_rgb)
plt.title("original")

plt.subplot(1,2,2)
plt.imshow(rotated)
plt.title("rotated")

plt.show()

# affine , linear , sclae


image = cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

scale_x = 8
scale_y = 6

scaled = cv2.resize(image_rgb,None , fx=scale_x , fy=scale_y , interpolation=cv2.INTER_LINEAR)


plt.subplot(1,2,1)
plt.imshow(image_rgb)
plt.title("original")

plt.subplot(1,2,2)
plt.imshow(scaled)
plt.title("scaled")

plt.show()

# affine, linear,shear
import numpy as np

image = cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

width,height = image_rgb.shape[:2]

kx = 0.5

M = np.float32([[1,kx,0],[0,1,0]])

new_width = int(width+abs(kx)*height)

sheared = cv2.warpAffine(image_rgb , M,(new_width,height))

plt.subplot(1,2,1)
plt.imshow(image_rgb)
plt.title("original")

plt.subplot(1,2,2)
plt.imshow(sheared)
plt.title("sheared")

plt.show()

# rotation , uniform scaling , translation

image = cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

height,width = image_rgb.shape[:2]

tx = 100
ty = 50

M = np.float32([[1,0,tx],[0,1,ty]])

translated = cv2.warpAffine(image_rgb , M , (width,height))

plt.subplot(1,2,1)
plt.imshow(image_rgb)
plt.title("original")

plt.subplot(1,2,2)
plt.imshow(translated)
plt.title("trans")

plt.show()

# rigid transformation
image = cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

height,width = image_rgb.shape[:2]

center = (width//2,height//2)
angle=45
scale=1

M = cv2.getRotationMatrix2D(center,angle,scale)

M[0,2]+=100
M[1,2]+=50

rigid = cv2.warpAffine(image_rgb,M,(width,height))

plt.subplot(1,2,1)
plt.imshow(image_rgb)
plt.title("original")

plt.subplot(1,2,2)
plt.imshow(rigid)
plt.title("rigid")

plt.show()

#projective prespection

image = cv2.imread(image_path)

image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)

height,width = image_rgb.shape[:2]

src_points = np.float32([[0,0], [width-1,0] , [width-1,height-1], [0,height-1]])

dst_points = np.float32([[100,50],[width-150,0],[width-50,height-50],[50,height-20]])

M = cv2.getPerspectiveTransform(src_points,dst_points)

persp = cv2.warpPerspective(image_rgb,M,(width,height))


plt.subplot(1,2,1)
plt.imshow(image_rgb)
plt.title("original")

plt.subplot(1,2,2)
plt.imshow(persp)
plt.title("persp")

plt.show()


# undo a 45° rotation without chopping corners
ang = 45; t = np.deg2rad(ang)
new_w = int(h*abs(np.sin(t)) + w*abs(np.cos(t)))
new_h = int(h*abs(np.cos(t)) + w*abs(np.sin(t)))
R = np.array([[np.cos(t),-np.sin(t)], [np.sin(t), np.cos(t)]]) # manual 2x2 (sine & cosine)
shift = np.array([new_w/2, new_h/2]) - R @ np.array([w/2, h/2]) # re-centre on the bigger canvas
M = np.hstack([R, shift[:, None]]).astype(np.float32)
fixed = cv2.warpAffine(img, M, (new_w, new_h))

# xray enhancement
xr = cv2.imread('data/samplexray.png', cv2.IMREADGRAYSCALE) # relative path!
if xr is None: raise SystemExit('image not found')
eq = cv2.equalizeHist(xr)
heat = cv2.applyColorMap(eq, cv2.COLORMAP
JET)
_
f = heat.astype(np.float32); m = f.reshape(-1,3).mean(0)
bal = np.clip(f + (m.mean() - m), 0, 255).astype(np.uint8)
_, dense = cv2.threshold(eq, 200, 255, cv2.THRESH
BINARY)
_
log_
x = (255/np.log(1+xr.max()) * np.log(1 +
xr.astype(np.float32))).astype(np.uint8)
gam
_
x = cv2.LUT(xr, np.array([(i/255)**0.6*255 for i in range(256)],
np.uint8)) # gamma 0.6
# plot: raw | equalized | heatmap | balanced | dense mask | log | gamma, then
cv2.imwrite('output/...')

# ct + mri



# video read
cap = cv2.VideoCapture('data/echo.mp4') # file path, not 0
(0 = webcam)
while True:
if not cap.isOpened(): raise SystemExit('cannot open video')
ok, frame = cap.read() # ok=False at end of
video
if not ok: break
gray = cv2.cvtColor(frame, cv2.COLOR
BGR2GRAY)
_
eq = cv2.equalizeHist(gray)
heat = cv2.applyColorMap(eq, cv2.COLORMAP
JET)
_
f = heat.astype(np.float32); m = f.reshape(-1,3).mean(0)
f = np.clip(f + (m.mean() - m), 0, 255) # colour balance
f = 255/np.log(1+f.max()) * np.log(1+f) # log: reveal dark
chambers
f = 255 * (f/255) ** 1.5 # power-law gamma>1:
suppress bright backscatter
out = f.astype(np.uint8)
cv2.imshow('Raw | Enhanced'
, np.hstack([frame, out])) # same height,
same channels required
if cv2.waitKey(25) & 0xFF == ord('q'): break
cap.release(); cv2.destroyAllWindows()
