# -*- coding: utf-8 -*-
"""Lab_05_Manual_Extracted_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyE8i-daUikpBDbNo-DGY4AU5T36pkP3

# Lab 05 Manual — Extracted Python Code

The code below is transcribed from the **Lab 05 Manual.pdf**, under its corresponding section headings. Lines wrapped by the PDF layout have been joined into valid Python statements. The example image filenames remain as printed in the manual: `image.jpg`, `ents.jpg`, `dog.jpeg`, and `dogimg.jpg`. Put those images beside the notebook or edit the filenames before running. The `cv2.imshow()` lines in the K-Means example require a desktop Python environment.
"""

## Global Thresholding — manual page 7

import cv2

image = cv2.imread('image.jpg', cv2.IMREAD_GRAYSCALE)
_, binary_mask = cv2.threshold(image, 128, 255, cv2.THRESH_BINARY)

#Adaptive Thresholding
import cv2

image = cv2.imread('image.jpg', cv2.IMREAD_GRAYSCALE)
binary_mask = cv2.adaptiveThreshold(image, 255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)

# Otsu’s Thresholding

import cv2

image = cv2.imread('image.jpg', cv2.IMREAD_GRAYSCALE)
_, binary_mask = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY +
                               cv2.THRESH_OTSU)

#Color-Based Thresholding

import cv2
import numpy as np

image = cv2.imread('image.jpg')
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
lower_bound = np.array([30, 50, 50])
upper_bound = np.array([60, 255, 255])
mask = cv2.inRange(hsv_image, lower_bound, upper_bound)

# Hysteresis Thresholding (Canny Edge Detector)
import cv2
image = cv2.imread('image.jpg', cv2.IMREAD_GRAYSCALE)
edges = cv2.Canny(image, 100, 200)

# Region Growing

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the image
image = cv2.imread('ents.jpg', cv2.IMREAD_GRAYSCALE)

# Initialize seed point (starting point for region growing)
seed_point = (10, 10)

# Define a function for region growing
def region_growing(image, seed, threshold):
    # Create an empty mask to store the segmented region
    mask = np.zeros_like(image, dtype=np.uint8)

    # Create a stack for pixel traversal
    stack = [seed]

    # Get the intensity value of the seed point
    seed_intensity = image[seed]

    while stack:
        x, y = stack.pop()

        # Check if the pixel is within the image boundaries
        if x < 0 or x >= image.shape[0] or y < 0 or y >= image.shape[1]:
            continue

        # Check if the pixel is unvisited
        if mask[x, y] == 0:
            # Check if the intensity difference is below the threshold
            if abs(int(image[x, y]) - int(seed_intensity)) < threshold:
                # Add the pixel to the segmented region
                mask[x, y] = 255

                # Add neighboring pixels to the stack
                stack.extend([(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)])

    return mask

# Define a threshold
threshold = 50

# Perform region growing
segmented_image = region_growing(image, seed_point, threshold)

# # Display the segmented image
# cv2.imshow('Segmented Image', segmented_image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

plt.imshow(segmented_image)
plt.axis('off')
plt.show()

# Watershed Segmentation

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the image
image = cv2.imread('image.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Threshold the image to create markers (you can adjust the threshold value)
_, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV +
                          cv2.THRESH_OTSU)

# Perform morphological operations to remove noise
kernel = np.ones((5, 5), np.uint8)
opening = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel, iterations=2)

# Create sure background and sure foreground markers
sure_bg = cv2.dilate(opening, kernel, iterations=3)
dist_transform = cv2.distanceTransform(opening, cv2.DIST_L2, 5)
_, sure_fg = cv2.threshold(dist_transform, 0.2 * dist_transform.max(), 255, 0)

# Subtract sure foreground from sure background to get unknown region
sure_fg = np.uint8(sure_fg)
unknown = cv2.subtract(sure_bg, sure_fg)

# Label markers for watershed algorithm
_, markers = cv2.connectedComponents(sure_fg)
markers = markers + 1
markers[unknown == 255] = 0

# Apply watershed algorithm
cv2.watershed(image, markers)
image[markers == -1] = [255, 0, 0]  # Mark boundaries with red color

plt.imshow(image)
plt.axis('on')
plt.show()

# Clustering-Based Segmentation

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the image
image = cv2.imread('dogimg.jpg')

# Reshape the image to a 2D array of pixels
pixel_values = image.resize((-1, 3))

# Convert to float32 for K-Means clustering
pixel_values = np.float32(pixel_values)

# Define criteria and apply K-Means clustering
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.2)
K = 4  # Number of clusters (you can adjust this)
_, labels, centers = cv2.kmeans(pixel_values, K, None, criteria, 10,
                                cv2.KMEANS_RANDOM_CENTERS)

# Convert back to 8-bit values
centers = np.uint8(centers)
segmented_image = centers[labels.flatten()]

# Reshape the segmented image back to its original shape
segmented_image = segmented_image.reshape(image.shape)

# Display the segmented image
cv2.imshow('Segmented Image', segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

plt.imshow(segmented_image)
plt.axis('on')
plt.show()

